<a href="https://colab.research.google.com/github/shernee/04_cmpe258/blob/main/DemoTensoflow_pytorch_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow operations

#Boradcasting

In [ ]:
#import library
import tensorflow as tf
import numpy as np

In [ ]:
#sample data
sample_data = tf.constant([4,5,6,7])
print("This is a Sample data:",sample_data)

This is a Sample data: tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)


In [ ]:
#broadcast sample data
broadcast_data = tf.broadcast_to(sample_data, [4,4])
print("This is the data after broadcasting:",broadcast_data)

This is the data after broadcasting: tf.Tensor(
[[4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]], shape=(4, 4), dtype=int32)


In [ ]:
#tensor with float values
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)



tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
#Tensor with three axis
rank_2_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_2_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
#converting tensor to numpy
np.array(rank_2_tensor)
rank_2_tensor.numpy()

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)

In [ ]:
#smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.
#The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [ ]:
#same operations without broadcasting
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [ ]:
#Most of the time, broadcasting is both time and space efficient, as the broadcast operation never materializes the expanded tensors in memory.
#You see what broadcasting looks like using tf.broadcast_to

print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


#Ragged Tensors

In [ ]:
#A tensor with variable numbers of elements along some axis is called "ragged". Use tf.ragged.RaggedTensor for ragged data.
#For example, This cannot be represented as a regular tensor

ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [ ]:
print(ragged_tensor.shape)

(4, None)


#Sparse tensors

In [ ]:
#Sometimes, your data is sparse, like a very wide embedding space. TensorFlow supports tf.sparse.SparseTensor and related operations to store sparse data efficiently.
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


#String tensors

In [ ]:
#The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the axes of the tensor
#scalar string tensor
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In [ ]:
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [ ]:
# You can use split to split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [ ]:
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


In [ ]:
#convert string to a number
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [ ]:
#converting string to bytes and then to numbers
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [ ]:
#splitting strings as unicode and then decode it
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


#Named tensors

In [ ]:

my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])
# Create a and b; they will have the same name but will be backed by
# different tensors.
a = tf.Variable(my_tensor, name="Mark")
# A new variable with the same name, but different value
# Note that the scalar add is broadcast
b = tf.Variable(my_tensor + 1, name="Mark")

# These are elementwise-unequal, despite having the same name
print(a == b)

tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)


#Operations in Pytorch

#Broadcasting

In [ ]:
import torch

In [ ]:
tensor1 = torch.tensor([[1, 2], [0, 3]])
tensor2 = torch.tensor([[3, 1]])
tensor3 = torch.tensor([[5], [2]])
tensor4 = torch.tensor([7])

print(tensor1.shape)
# Outputs- torch.Size([2, 2])
print(tensor2.shape)
# Outputs- torch.Size([1, 2])
print(tensor3.shape)
# Outputs- torch.Size([2, 1])
print(tensor4.shape)
# Outputs- torch.Size([1])

print(tensor1 + tensor2)
# Outputs- tensor([[4, 3], [3, 4]])
print(tensor1 + tensor3)
# Outputs- tensor([[6, 7], [2, 5]])
print(tensor2 + tensor3)
# Outputs- tensor([[8, 6], [5, 3]])
print(tensor1 + tensor4)
# Outputs- tensor([[ 8, 9], [ 7, 10]])

torch.Size([2, 2])
torch.Size([1, 2])
torch.Size([2, 1])
torch.Size([1])
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


#Ragged Tensors - Nested tensors

In [ ]:
a = torch.randn(20, 128) # text 1
nt = torch.nested.nested_tensor([a, a], dtype=torch.float32)
nt.size(0)
2
nt.size(1)
20
nt.size(2)
128
torch.stack(nt.unbind()).size()
torch.Size([2, 20, 128])
torch.stack([a, a]).size()
torch.Size([2, 20, 128])
torch.equal(torch.stack(nt.unbind()), torch.stack([a, a]))


/usr/local/lib/python3.8/dist-packages/torch/nested/__init__.py:47: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:175.)
  nt = torch._nested_tensor_from_tensor_list(new_data, dtype, None, device, pin_memory)


True

#Sparse Tensors

In [ ]:
a = torch.tensor([[0, 2.], [3, 0]])
a.to_sparse()

tensor(indices=tensor([[0, 1],
                       [1, 0]]),
       values=tensor([2., 3.]),
       size=(2, 2), nnz=2, layout=torch.sparse_coo)

In [ ]:
t = torch.tensor([[[1., 0], [2., 3.]], [[4., 0], [5., 6.]]])
t.dim()
t.to_sparse_csr()

<ipython-input-33-75483179f322>:3: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at ../aten/src/ATen/SparseCsrTensorImpl.cpp:54.)
  t.to_sparse_csr()


tensor(crow_indices=tensor([[0, 1, 3],
                            [0, 1, 3]]),
       col_indices=tensor([[0, 0, 1],
                           [0, 0, 1]]),
       values=tensor([[1., 2., 3.],
                      [4., 5., 6.]]), size=(2, 2, 2), nnz=3,
       layout=torch.sparse_csr)

#Named tensors

In [ ]:
#Factory functions take a new names argument that associates a name with each dimension.
torch.zeros(2, 3, names=('N', 'C'))



<ipython-input-34-09d92866311e>:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  torch.zeros(2, 3, names=('N', 'C'))


tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('N', 'C'))

In [ ]:
imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W'))
imgs.names
renamed_imgs = imgs.rename(H='height', W='width')
renamed_imgs.names

('N', 'C', 'height', 'width')

In [ ]:
x = torch.randn(3, names=('X',))
y = torch.randn(3)
z = torch.randn(3, names=('Z',))

In [ ]:
(x + y).names
(x + x).names

('X',)

#String tensors

In [ ]:
#There is no string tensor so you cannot directly convert to pytorch tensor of strings.
#Alternative, you can convert the string to ASCII char values and save that as a Tensor
#or use scikit to encode strings and convert to tensors
from sklearn import preprocessing
labels = ['cat', 'dog', 'mouse', 'elephant', 'pandas']
le = preprocessing.LabelEncoder()
targets = le.fit_transform(labels)
targets = torch.as_tensor(targets)
print(targets)

tensor([0, 1, 3, 2, 4])


#Implement linear search using tensor flow

In [ ]:
#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
# import tensorflow.compat.v1 as tf
import tensorflow._api.v2.compat.v1 as v1
v1.disable_v2_behavior()

import numpy as np



class LinearSearch():
    def __init__(self, array, x):
        self.x = tf.constant(x)
        self.array = tf.constant(array)
        self.length = len(array)
        self.graph = tf.while_loop(self.cond, self.body, [0, self.x, False],
                            back_prop=False)

    def run(self):
        with tf.compat.v1.Session() as sess:
            tf.compat.v1.disable_eager_execution()
            tf.compat.v1.global_variables_initializer().run()
            return sess.run(self.graph)

    def cond(self, i, _, is_found):
        return tf.logical_and(tf.less(i, self.length), tf.logical_not(is_found))

    def body(self, i, _, is_found):
        return tf.cond(tf.equal(self.array[i], self.x),
                    lambda: (i, self.array[i], True),
                    lambda: (tf.add(i, 1), -1, False))

if __name__ == '__main__':
    array, x = [20, 70, 33, 84], 33
    search = LinearSearch(array, x)
    ix, xx, is_found = ret = search.run()
    print('Array :', array)
    print('Number to search :', x)
    if is_found:
        print('{} is at index {}.'.format(xx, ix))
    else:
        print('Not found.')

Array : [20, 70, 33, 84]
Number to search : 33
33 is at index 2.


#Implement Binary search using tensor flow

In [ ]:
#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
# import tensorflow.compat.v1 as tf
import tensorflow._api.v2.compat.v1 as v1
v1.disable_v2_behavior()

import numpy as np



class BinarySearch():
    def __init__(self, array, x):
        self.array = tf.constant(array)
        self.x = tf.constant(x)
        self.loop = tf.while_loop(self.cond, self.body, [-1,False,0,len(array),-1],
                        back_prop=False)

    def run(self):
        with tf.compat.v1.Session() as sess:
            tf.compat.v1.disable_eager_execution()
            tf.compat.v1.global_variables_initializer().run()
            return sess.run(self.loop)

    def cond(self, x, is_found, left, right, mid):
        return tf.logical_and(tf.less_equal(left, right), tf.logical_not(is_found))

    def body(self, x, is_found, left, right, mid):
        mid = tf.cast(tf.divide(tf.add(left, right), 2),tf.int32)
        return tf.cond(tf.equal(self.array[mid], self.x),
                    lambda: (self.array[mid], True, left, right, mid),
                    lambda: tf.cond(tf.less(self.array[mid], self.x),
                                lambda: (-1, False, tf.add(mid, 1), right, mid),
                                lambda: (-1, False, left, tf.subtract(mid, 1), mid)))

if __name__ == '__main__':
    array = sorted([10, 30, 52, 74, 84])
    x = 52
    search = BinarySearch(array, x)
    xx, is_found, l, r, m = search.run()

    print('Array :', array)
    print('Number to search :', x)
    if is_found:
        print('{} is at index {}.'.format(xx, m))
    else:
        print('Not found.')

Array : [10, 30, 52, 74, 84]
Number to search : 52
52 is at index 2.


#Insertion sort using tensor flow

In [ ]:
#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow._api.v2.compat.v1 as v1
v1.disable_v2_behavior()
np.random.seed(123)


class InsertionSort():
    def __init__(self, array):
        self.i = tf.constant(1)
        self.j = tf.constant(len(array)-1)
        self.array = tf.Variable(array, trainable=False)
        self.length = len(array)

        cond = lambda i, j, _: tf.less(i-1, self.length-1)
        self.graph = tf.while_loop(cond, self.outer_loop, loop_vars=[self.i, self.j, self.array],
                shape_invariants=[self.i.get_shape(), self.j.get_shape(), tf.TensorShape(self.length)],
                parallel_iterations=1,
                back_prop=False)

    def run(self):
        with tf.compat.v1.Session() as sess:
            tf.compat.v1.disable_eager_execution()
            tf.compat.v1.global_variables_initializer().run()
            return sess.run(self.graph)

    def outer_loop(self, i, j, _):
        j = i
        cond = lambda i, j, array: tf.logical_and(tf.greater(j,0), tf.greater(array[j-1], array[j]))

        loop = tf.while_loop(cond, self.inner_loop, loop_vars=[i, j, self.array],
                    shape_invariants=[i.get_shape(), j.get_shape(), tf.TensorShape(self.length)],
                    parallel_iterations=1,
                    back_prop=False)
        return tf.add(i, 1), loop[1], loop[2]

    def inner_loop(self, i, j, _):
        return i, tf.subtract(j, 1), tf.compat.v1.scatter_nd_update(self.array, [[j-1],[j]], [self.array[j],self.array[j-1]])


with tf.compat.v1.Session() as sess:
    x = np.array([1.,7.,3.,8.])
    print(x)
    print(InsertionSort(x).run()[2])
    y = np.random.rand(10)
    print(y)
    print(InsertionSort(y).run()[2])

[1. 7. 3. 8.]
[1. 3. 7. 8.]
[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]
[0.22685145 0.28613933 0.39211752 0.42310646 0.4809319  0.55131477
 0.68482974 0.69646919 0.71946897 0.9807642 ]
