<a href="https://colab.research.google.com/github/shernee/04_cmpe258/blob/main/Operations_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Scalar vector multiplication

a = np.array([4])
b = np.array([1, 5, 6, 8])
mult = np.einsum('i, i -> i', a, b)
print(a)
print(b)
print(mult)

[4]
[1 5 6 8]
[ 4 20 24 32]


In [ ]:
# Vector vector multiplication

a = np.random.randn(3, 4)
b = np.random.randn(4, 2)
mult = np.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

[[ 0.76497757 -0.78224885 -0.00681621 -1.51942336]
 [ 0.09455746  0.76844526  0.8387034  -0.18537236]
 [-1.22485349  0.98785641 -0.43627258 -0.47536971]]
[[ 2.15345824  0.92843212]
 [ 0.63841795  0.33498397]
 [-1.04038538  0.46885975]
 [-1.12889156  0.36509375]]
[[ 2.87030125 -0.1097389 ]
 [ 0.03090531  0.67076301]
 [-1.01647311 -1.18438242]]


In [ ]:
# Outer product

a = np.arange(1, 5)
b = np.arange(4, 7)  
prod = np.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

[1 2 3 4]
[4 5 6]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]
 [16 20 24]]


In [ ]:
# Scalar dot product

a = np.arange(12).reshape(4, 3)
b = np.arange(6).reshape(3, 2)
prod = np.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
362


In [ ]:
# Hadamard product

a = np.arange(8).reshape(2, 4)
b = np.arange(4, 12).reshape(2, 4)
prod = np.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)

[[0 1 2 3]
 [4 5 6 7]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  5 12 21]
 [32 45 60 77]]


In [ ]:
# Batch matrix multiplication

a = np.random.randn(5, 3, 2)
b = np.random.randn(5, 2, 4)
batch_mult = np.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

[[[-1.59291952 -1.70408616]
  [-0.88246457  0.33395543]
  [ 0.03307851 -0.62974716]]

 [[-0.59962721  0.68693546]
  [-0.11948422  0.83436101]
  [ 0.04022123  0.16925315]]

 [[ 0.75698376 -0.64018276]
  [ 0.13460964 -1.32834147]
  [-0.67345709  0.2167815 ]]

 [[-1.15595122  0.91098702]
  [ 0.60854487 -1.65085271]
  [-0.49000428  0.22108351]]

 [[-0.73022286 -0.14121195]
  [-0.52224592  2.47480415]
  [ 0.30442298 -0.2882491 ]]]
[[[ 0.24068131 -0.88231674  0.1799716   1.46981434]
  [ 0.04296022  0.49138514  0.71826589  0.34366977]]

 [[ 0.89354168  0.10104235  1.34472365 -0.78041617]
  [ 1.08114172  1.02827283  0.03495368 -1.65898781]]

 [[ 0.97899352 -0.72557687  0.54917271  0.4438784 ]
  [ 2.04793206  1.53992581  0.36409474  1.48365976]]

 [[ 0.2434217  -0.30487748  1.47718862 -0.27778258]
  [ 0.27376563  1.37761836  1.41753625  0.08503235]]

 [[-1.52164624 -0.2721568   0.92518351  1.75260769]
  [ 0.27548066  1.3369977  -0.24369095 -1.25930769]]]
[[[-0.45659387  0.56809693 -1.51066723 -

In [ ]:
# Tensor reduction

a = np.random.randn(3, 3, 5, 4)
b = np.random.randn(5, 1, 3, 11, 5)
reduction = np.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(3, 3, 5, 4) (5, 1, 3, 11, 5) (3, 4, 5, 1, 11)


In [ ]:
# Transpose

a = np.arange(10).reshape(5, 2)
transpose = np.einsum('ij -> ji', a)
print(a)
print(transpose)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [ ]:
# Bilinear transformation

a = np.random.randn(2, 4)
b = np.random.randn(3, 4, 4)
c = np.random.randn(2, 4)
bilinear = np.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

[[-1.92600697  0.67942168  0.64854055  0.43460609]
 [ 1.34870619  0.89655495 -1.83264634 -1.03112595]]
[[[ 1.0314865   0.46768561 -1.47391665  1.82494775]
  [-0.54838931 -0.01578414  0.89794506  1.4814173 ]
  [ 1.3689206   1.12468422 -1.23451401  1.70285858]
  [-0.21129999 -0.89286092 -0.16649975  1.64050178]]

 [[-2.59564182  1.07032398  0.40438749 -0.34822429]
  [-0.48797635  1.22744929  1.6651854  -1.92973965]
  [ 0.70925154  0.26532026 -0.31602757  2.06057205]
  [ 0.04430595 -2.84181978 -0.52599354  0.14882191]]

 [[ 0.05362048  1.30576621 -0.04199027  1.21447977]
  [ 1.4057704   1.22958202 -0.84998361  0.7432612 ]
  [ 0.92317916  1.37705184  0.64381896  0.77533576]
  [-0.23498203  0.00424315  0.68880479 -0.08012529]]]
[[-1.02085627  0.39937674  0.80827532 -0.43283131]
 [ 0.86902032 -1.24128796 -0.36748349  0.77991954]]
[[  3.74927432  -6.563761    -0.92056933]
 [ -1.81637452 -16.72504112   1.2309075 ]]


In [ ]:
# Attention

# Parameters
# [hidden_dimension]
bM = np.random.randn(6)
br = np.random.randn(6) 
w = np.random.randn(6)
# [hidden_dimension x hidden_dimension]
WY = np.random.randn(6, 6)
Wh = np.random.randn(6, 6)
Wr = np.random.randn(6, 6)
Wt = np.random.randn(6, 6)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = np.einsum('ik, kl -> il', ht, Wh) + np.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = np.expand_dims(tmp, 1)
  tmp_tiled = np.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = np.tanh(np.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = np.einsum('ijk, k -> ij', Mt, w)
  at = np.exp(at)/np.sum(np.exp(at))
  
  # [batch_size x hidden_dimension]
  rt = np.einsum('ijk, ij -> ik', Y, at) + np.tanh(np.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = np.random.randn(3,5,6)
# [batch_size x hidden_dimension]
ht = np.random.randn(3, 6)
rt1 = np.random.randn(3, 6)

rt, at = attention(Y, ht, rt1)

print(at)

[[0.00615517 0.00840162 0.01275558 0.02768632 0.0268708 ]
 [0.01143558 0.00967309 0.00876322 0.00082646 0.00636584]
 [0.14539563 0.24770076 0.09354095 0.02113665 0.37329233]]


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return np.expand_dims(zl, 1) + np.tanh(np.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = np.random.rand(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = np.random.rand(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = np.random.rand(5, 3, 3)

transition(zl)

array([[[1.17732557, 1.74257814, 0.97735291],
        [1.0616197 , 1.51811389, 0.84987458],
        [1.04991183, 1.79311996, 1.00403865],
        [0.958174  , 1.87415546, 0.85454942],
        [0.44555117, 1.86805333, 0.86880233]],

       [[1.37051076, 0.87571551, 0.69239961],
        [1.06392376, 0.59878613, 0.63906969],
        [1.28320333, 1.03184968, 0.87489853],
        [1.17516827, 0.99816043, 0.63869989],
        [0.71255258, 0.90047342, 0.65352216]]])