<a href="https://colab.research.google.com/github/shernee/04_cmpe258/blob/main/Tensorflow%2Bpytorch_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow operations

In [ ]:
#import library
import tensorflow as tf
import numpy as np

## Broadcasting

In [ ]:
#sample data
sample_data = tf.constant([2,3,4])
print("sample data:",sample_data)

sample data: tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [ ]:
# broadcast sample data
broadcast_data = tf.broadcast_to(sample_data, [3,3])
print("Sample data after broadcasting:",broadcast_data)

Sample data after broadcasting: tf.Tensor(
[[2 3 4]
 [2 3 4]
 [2 3 4]], shape=(3, 3), dtype=int32)


In [ ]:
#tensor with float values
rank1_tensor = tf.constant([5.0, 6.0, 7.0, 8.0])
print(rank1_tensor)

tf.Tensor([5. 6. 7. 8.], shape=(4,), dtype=float32)


In [ ]:
#Tensor with three axes
rank2_tensor = tf.constant([
  [[0, 4, 2, 60],
   [5, 7, 10, 8]],
  [[10, 19, 12, 13],
   [15, 31, 28, 18]],
  [[20, 16, 22, 31],
   [9, 26, 49, 20]],])

print(rank2_tensor)

tf.Tensor(
[[[ 0  4  2 60]
  [ 5  7 10  8]]

 [[10 19 12 13]
  [15 31 28 18]]

 [[20 16 22 31]
  [ 9 26 49 20]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
#converting tensor to numpy
np.array(rank2_tensor)
rank2_tensor.numpy()

array([[[ 0,  4,  2, 60],
        [ 5,  7, 10,  8]],

       [[10, 19, 12, 13],
        [15, 31, 28, 18]],

       [[20, 16, 22, 31],
        [ 9, 26, 49, 20]]], dtype=int32)

In [ ]:
#This is a case of "stretching", when you multiply or add a tensor to a scalar. The scalar is broadcast to the same shape as the tensor.
x = tf.constant([1, 7, 3])

y = tf.constant(5)
z = tf.constant([5, 5, 5])
# These three end up being computationally similar
print(tf.multiply(x, 5))
print(x * y)
print(x * z)

tf.Tensor([ 5 35 15], shape=(3,), dtype=int32)
tf.Tensor([ 5 35 15], shape=(3,), dtype=int32)
tf.Tensor([ 5 35 15], shape=(3,), dtype=int32)


In [ ]:
#same operations without broadcasting
x_stretch = tf.constant([[1, 1, 1],
                         [3, 3, 3],
                         [5, 5, 5]])

y_stretch = tf.constant([[1, 3, 5],
                         [1, 3, 5],
                         [1, 3, 5]])

print(x_stretch * y_stretch) 

tf.Tensor(
[[ 1  3  5]
 [ 3  9 15]
 [ 5 15 25]], shape=(3, 3), dtype=int32)


In [ ]:
#tf.broadcast_to

print(tf.broadcast_to(tf.constant([3, 5, 7]), [3, 3]))

tf.Tensor(
[[3 5 7]
 [3 5 7]
 [3 5 7]], shape=(3, 3), dtype=int32)


## Ragged Tensors

In [ ]:
#A tensor with variable numbers of elements along some axis is called "ragged".

ragged_list = [
    [0, 7, 2, 9],
    [1, 7],
    [7, 7, 7],
    [11]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 7, 2, 9], [1, 7], [7, 7, 7], [11]]>


In [ ]:
print(ragged_tensor.shape)

(4, None)


## Sparse tensors

In [ ]:
# When data is sparese, sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 1], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[4, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


## String tensors

In [ ]:
#scalar string tensor - length of string is not represented as an axis value
scalar_string_tensor = tf.constant("This is true")
print(scalar_string_tensor)

tf.Tensor(b'This is true', shape=(), dtype=string)


In [ ]:
tensor_of_strings = tf.constant(["This is true",
                                 "Only this",
                                 "Not that"])

print(tensor_of_strings)
# string length is not an axis value

tf.Tensor([b'This is true' b'Only this' b'Not that'], shape=(3,), dtype=string)


In [ ]:
# split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'This' b'is' b'true'], shape=(3,), dtype=string)


In [ ]:
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'This', b'is', b'true'], [b'Only', b'this'], [b'Not', b'that']]>


In [ ]:
#convert string to a number
text = tf.constant("2 50 200")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  2.  50. 200.], shape=(3,), dtype=float32)


In [ ]:
#converting string to bytes and then to numbers
byte_strings = tf.strings.bytes_split(tf.constant("String"))
byte_ints = tf.io.decode_raw(tf.constant("String"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'S' b't' b'r' b'i' b'n' b'g'], shape=(6,), dtype=string)
Bytes: tf.Tensor([ 83 116 114 105 110 103], shape=(6,), dtype=uint8)


In [ ]:
#splitting strings as unicode and then decode it
unicode_bytes = tf.constant("₹ヒ😒 ಉ")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe2\x82\xb9\xe3\x83\x92\xf0\x9f\x98\x92 \xe0\xb2\x89', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe2\x82\xb9' b'\xe3\x83\x92' b'\xf0\x9f\x98\x92' b' ' b'\xe0\xb2\x89'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([  8377  12498 128530     32   3209], shape=(5,), dtype=int32)


## Named tensors

In [ ]:
my_tensor = tf.constant([[1.0, 2.0, 3.0], [11.0, 12.0, 13.0]])
my_variable = tf.Variable(my_tensor)

# Different types of variables
bool_variable = tf.Variable([False, True, False])
complex_variable = tf.Variable([5 + 10j, 6 + 12j])
# a and b have the same name but different tensors.
a = tf.Variable(my_tensor, name="Jake")
# same name, different value
b = tf.Variable(my_tensor + 2, name="Jake")

print("Are a and b equal", a == b)

Are a and b equal tf.Tensor(
[[False False False]
 [False False False]], shape=(2, 3), dtype=bool)


#Operations in Pytorch

In [ ]:
import torch

## Broadcasting

In [ ]:
tensor1 = torch.tensor([[1, 5], [6, 3]])
tensor2 = torch.tensor([[3, 2]])
tensor3 = torch.tensor([[5], [10]])
tensor4 = torch.tensor([8])

print(tensor1.shape)

print(tensor2.shape)

print(tensor3.shape)

print(tensor4.shape)


print(tensor1 + tensor2)

print(tensor1 + tensor3)

print(tensor2 + tensor3)

print(tensor1 + tensor4)


torch.Size([2, 2])
torch.Size([1, 2])
torch.Size([2, 1])
torch.Size([1])
tensor([[4, 7],
        [9, 5]])
tensor([[ 6, 10],
        [16, 13]])
tensor([[ 8,  7],
        [13, 12]])
tensor([[ 9, 13],
        [14, 11]])


## Ragged Tensors - Nested tensors

In [ ]:
a = torch.randn(30, 60) # text 1
nt = torch.nested.nested_tensor([a, a], dtype=torch.float32)
nt.size(0)
2
nt.size(1)
20
nt.size(2)
128
torch.stack(nt.unbind()).size()
torch.Size([2, 20, 128])
torch.stack([a, a]).size()
torch.Size([2, 20, 128])
torch.equal(torch.stack(nt.unbind()), torch.stack([a, a]))


/usr/local/lib/python3.8/dist-packages/torch/nested/__init__.py:47: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:175.)
  nt = torch._nested_tensor_from_tensor_list(new_data, dtype, None, device, pin_memory)


True

## Sparse Tensors

In [ ]:
a = torch.tensor([[0, 3.], [10, 0]])
a.to_sparse()

tensor(indices=tensor([[0, 1],
                       [1, 0]]),
       values=tensor([ 3., 10.]),
       size=(2, 2), nnz=2, layout=torch.sparse_coo)

In [ ]:
t = torch.tensor([[[1., 0], [2., 5.]], [[7., 0], [8., 6.]]])
t.dim()
t.to_sparse_csr()

<ipython-input-36-1dda343efd5a>:3: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at ../aten/src/ATen/SparseCsrTensorImpl.cpp:54.)
  t.to_sparse_csr()


tensor(crow_indices=tensor([[0, 1, 3],
                            [0, 1, 3]]),
       col_indices=tensor([[0, 0, 1],
                           [0, 0, 1]]),
       values=tensor([[1., 2., 5.],
                      [7., 8., 6.]]), size=(2, 2, 2), nnz=3,
       layout=torch.sparse_csr)

## Named tensors

In [ ]:
#Factory functions take a new names argument that associates a name with each dimension.
torch.zeros(2, 3, names=('A', 'S'))



<ipython-input-37-4c2c60ec320c>:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  torch.zeros(2, 3, names=('A', 'S'))


tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('A', 'S'))

In [ ]:
imgs = torch.randn(1, 2, 2, 3 , names=('A', 'S', 'H', 'W'))
imgs.names
renamed_imgs = imgs.rename(H='height', W='width')
renamed_imgs.names

('A', 'S', 'height', 'width')

In [ ]:
x = torch.randn(5, names=('N',))
y = torch.randn(5)
z = torch.randn(5, names=('P',))

In [ ]:
(x + y).names
(x + x).names

('N',)

## String tensors

In [ ]:
#The two ways to have string tensors is to convert a string toits ASCII values and save that as a tensor
#or encode strings using sklearn and convert the encodings to tensors
from sklearn import preprocessing
labels = ['have', 'a', 'nice', 'day']
le = preprocessing.LabelEncoder()
targets = le.fit_transform(labels)
targets = torch.as_tensor(targets)
print(targets)

tensor([2, 0, 3, 1])


#Implement linear search using tensor flow

In [ ]:
#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
# import tensorflow.compat.v1 as tf
import tensorflow._api.v2.compat.v1 as v1
v1.disable_v2_behavior()

import numpy as np

class LinearSearch():
    def __init__(self, array, x):
        self.x = tf.constant(x)
        self.array = tf.constant(array)
        self.length = len(array)
        self.graph = tf.while_loop(self.cond, self.body, [0, self.x, False],
                            back_prop=False)

    def run(self):
        with tf.compat.v1.Session() as sess:
            tf.compat.v1.disable_eager_execution()
            tf.compat.v1.global_variables_initializer().run()
            return sess.run(self.graph)

    def cond(self, i, _, is_found):
        return tf.logical_and(tf.less(i, self.length), tf.logical_not(is_found))

    def body(self, i, _, is_found):
        return tf.cond(tf.equal(self.array[i], self.x),
                    lambda: (i, self.array[i], True),
                    lambda: (tf.add(i, 1), -1, False))

if __name__ == '__main__':
    array, x = [1, 100, 25, 50, 500], 25
    search = LinearSearch(array, x)
    ix, xx, is_found = ret = search.run()
    print('Array to search :', array)
    print('Number to search :', x)
    if is_found:
        print('{} is at index {}.'.format(xx, ix))
    else:
        print('Number not found.')

Instructions for updating:
non-resource variables are not supported in the long term
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))


Array to search : [1, 100, 25, 50, 500]
Number to search : 25
25 is at index 2.


#Implement Binary search using tensor flow

In [ ]:
#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
# import tensorflow.compat.v1 as tf
import tensorflow._api.v2.compat.v1 as v1
v1.disable_v2_behavior()

import numpy as np

class BinarySearch():
    def __init__(self, array, x):
        self.array = tf.constant(array)
        self.x = tf.constant(x)
        self.loop = tf.while_loop(self.cond, self.body, [-1,False,0,len(array),-1],
                        back_prop=False)

    def run(self):
        with tf.compat.v1.Session() as sess:
            tf.compat.v1.disable_eager_execution()
            tf.compat.v1.global_variables_initializer().run()
            return sess.run(self.loop)

    def cond(self, x, is_found, left, right, mid):
        return tf.logical_and(tf.less_equal(left, right), tf.logical_not(is_found))

    def body(self, x, is_found, left, right, mid):
        mid = tf.cast(tf.divide(tf.add(left, right), 2),tf.int32)
        return tf.cond(tf.equal(self.array[mid], self.x),
                    lambda: (self.array[mid], True, left, right, mid),
                    lambda: tf.cond(tf.less(self.array[mid], self.x),
                                lambda: (-1, False, tf.add(mid, 1), right, mid),
                                lambda: (-1, False, left, tf.subtract(mid, 1), mid)))

if __name__ == '__main__':
    array = sorted([21, 10, 42, 60, 5])
    x = 21
    search = BinarySearch(array, x)
    xx, is_found, l, r, m = search.run()

    print('Array to search:', array)
    print('Number to search :', x)
    if is_found:
        print('{} is at index {}.'.format(xx, m))
    else:
        print('Number not found.')

Array to search: [5, 10, 21, 42, 60]
Number to search : 21
21 is at index 2.


#Insertion sort using tensor flow

In [ ]:
#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow._api.v2.compat.v1 as v1
v1.disable_v2_behavior()
np.random.seed(123)


class InsertionSort():
    def __init__(self, array):
        self.i = tf.constant(1)
        self.j = tf.constant(len(array)-1)
        self.array = tf.Variable(array, trainable=False)
        self.length = len(array)

        cond = lambda i, j, _: tf.less(i-1, self.length-1)
        self.graph = tf.while_loop(cond, self.outer_loop, loop_vars=[self.i, self.j, self.array],
                shape_invariants=[self.i.get_shape(), self.j.get_shape(), tf.TensorShape(self.length)],
                parallel_iterations=1,
                back_prop=False)

    def run(self):
        with tf.compat.v1.Session() as sess:
            tf.compat.v1.disable_eager_execution()
            tf.compat.v1.global_variables_initializer().run()
            return sess.run(self.graph)

    def outer_loop(self, i, j, _):
        j = i
        cond = lambda i, j, array: tf.logical_and(tf.greater(j,0), tf.greater(array[j-1], array[j]))

        loop = tf.while_loop(cond, self.inner_loop, loop_vars=[i, j, self.array],
                    shape_invariants=[i.get_shape(), j.get_shape(), tf.TensorShape(self.length)],
                    parallel_iterations=1,
                    back_prop=False)
        return tf.add(i, 1), loop[1], loop[2]

    def inner_loop(self, i, j, _):
        return i, tf.subtract(j, 1), tf.compat.v1.scatter_nd_update(self.array, [[j-1],[j]], [self.array[j],self.array[j-1]])


with tf.compat.v1.Session() as sess:
    x = np.array([1.,5.,8.,10.])
    print(x)
    print(InsertionSort(x).run()[2])
    y = np.random.rand(10)
    print(y)
    print(InsertionSort(y).run()[2])

[ 1.  5.  8. 10.]
[ 1.  5.  8. 10.]
[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]
[0.22685145 0.28613933 0.39211752 0.42310646 0.4809319  0.55131477
 0.68482974 0.69646919 0.71946897 0.9807642 ]
