<a href="https://colab.research.google.com/github/shernee/04_cmpe258/blob/main/Operations_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Scalar vector multiplication

a = np.array([3])
b = np.array([2, 4, 5])
mult = np.einsum('i, i -> i', a, b)
print(a)
print(b)
print(mult)

[3]
[2 4 5]
[ 6 12 15]


In [ ]:
# Vector vector multiplication

a = np.random.randn(2, 4)
b = np.random.randn(4, 3)
mult = np.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

[[-0.11934927 -0.53593219 -0.29954883 -0.82598512]
 [ 0.30859576 -0.22101905  2.24734413 -0.76500765]]
[[ 0.70546023  1.11469378  1.08872454]
 [-0.32524809 -0.11515271 -1.00738458]
 [-0.82427554 -1.91926268  0.62818331]
 [ 0.39667774  2.56422049 -0.12760272]]
[[ 0.00937562 -1.61441892  0.32717772]
 [-1.86630426 -5.90545129  2.06798809]]


In [ ]:
# Outer product

a = np.arange(1, 4)
b = np.arange(3, 6)  
prod = np.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

[1 2 3]
[3 4 5]
[[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]


In [ ]:
# Scalar dot product

a = np.arange(9).reshape(3, 3)
b = np.arange(6).reshape(3, 2)
prod = np.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]
204


In [ ]:
# Hadamard product

a = np.arange(8).reshape(2, 4)
b = np.arange(4, 12).reshape(2, 4)
prod = np.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)

[[0 1 2 3]
 [4 5 6 7]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  5 12 21]
 [32 45 60 77]]


In [ ]:
# Batch matrix multiplication

a = np.random.randn(3, 3, 2)
b = np.random.randn(3, 2, 2)
batch_mult = np.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

[[[ 1.86433145  0.18026446]
  [ 0.96088557 -0.21301206]
  [-0.04643046  0.79170105]]

 [[-0.58540443  0.90064271]
  [-0.47518076  0.17563139]
  [ 0.86782953 -0.09761453]]

 [[ 1.44671589 -0.2932761 ]
  [-0.82862753  0.74098226]
  [-0.99925666 -1.55405793]]]
[[[-0.70076012 -2.32418065]
  [ 0.15387008 -1.51448357]]

 [[-1.63722991 -0.44713199]
  [ 0.59479075 -1.31539766]]

 [[-0.17870871  0.25553315]
  [-0.59745724  0.22341117]]]
[[[-1.27871183 -4.60605067]
  [-0.70612647 -1.91066839]
  [ 0.15435572 -1.09110544]]

 [[ 1.4941356  -0.92295027]
  [ 0.88244408 -0.0185566 ]
  [-1.47889669 -0.25963242]]

 [[-0.0833208   0.30416271]
  [-0.29462226 -0.04619808]
  [ 1.10705902 -0.60253711]]]


In [ ]:
# Tensor reduction

a = np.random.randn(2, 3, 5, 7)
b = np.random.randn(4, 1, 3, 11, 5)
reduction = np.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [ ]:
# Transpose

a = np.arange(8).reshape(4, 2)
transpose = np.einsum('ij -> ji', a)
print(a)
print(transpose)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2 4 6]
 [1 3 5 7]]


In [ ]:
# Bilinear transformation

a = np.random.randn(2, 3)
b = np.random.randn(3, 3, 4)
c = np.random.randn(2, 4)
bilinear = np.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

[[ 0.41640901  1.41800761 -2.22496802]
 [ 1.64654931  1.74537677  0.79773514]]
[[[-1.69932846  1.79055169  0.0305436   1.32495446]
  [-0.74703826 -1.50608234 -0.47376777  0.78079651]
  [ 1.05611415 -1.29366924 -0.71599135  0.49904965]]

 [[ 0.64870706  0.842865   -0.74961891  0.62116627]
  [ 0.08356685  1.53921174 -1.17898801 -0.55020847]
  [-0.92471314 -0.35297612 -0.60085213 -0.68515161]]

 [[-0.77926431 -1.94745682 -1.04138851 -1.02385752]
  [-0.08367966  0.94740998  0.53848212  1.63230154]
  [ 1.16414273 -0.21094016 -1.01975626 -0.74647269]]]
[[ 1.0992388  -0.09824777  0.26039848 -0.75076202]
 [-1.53262903  0.11720155  0.2675521  -0.02427426]]
[[-4.84011849  1.44131073 -5.42061314]
 [ 4.45563454 -1.28277791  0.12655951]]


In [ ]:
# Attention

# Parameters
# [hidden_dimension]
bM = np.random.randn(7)
br = np.random.randn(7) 
w = np.random.randn(7)
# [hidden_dimension x hidden_dimension]
WY = np.random.randn(7, 7)
Wh = np.random.randn(7, 7)
Wr = np.random.randn(7, 7)
Wt = np.random.randn(7, 7)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = np.einsum('ik, kl -> il', ht, Wh) + np.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = np.expand_dims(tmp, 1)
  tmp_tiled = np.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = np.tanh(np.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = np.einsum('ijk, k -> ij', Mt, w)
  at = np.exp(at)/np.sum(np.exp(at))
  
  # [batch_size x hidden_dimension]
  rt = np.einsum('ijk, ij -> ik', Y, at) + np.tanh(np.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = np.random.randn(3,5,7)
# [batch_size x hidden_dimension]
ht = np.random.randn(3, 7)
rt1 = np.random.randn(3, 7)

rt, at = attention(Y, ht, rt1)

print(at)

[[0.00317547 0.00239202 0.00944615 0.00527305 0.00763736]
 [0.00148212 0.00367837 0.00268406 0.00591719 0.00120265]
 [0.17022494 0.10438838 0.00399219 0.01083727 0.66766876]]


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return np.expand_dims(zl, 1) + np.tanh(np.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = np.random.rand(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = np.random.rand(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = np.random.rand(5, 3, 3)

transition(zl)

array([[[1.58886753, 0.93715516, 1.51598914],
        [1.48697567, 0.98417538, 1.70563118],
        [1.84996775, 1.00643398, 1.45767282],
        [1.78632577, 1.02186328, 1.81872681],
        [1.73625986, 1.04220048, 1.79487834]],

       [[1.41130564, 1.30928501, 0.8278695 ],
        [1.25062753, 1.45039391, 0.87459487],
        [1.48043893, 1.46835651, 0.43535648],
        [1.45864525, 1.38918901, 0.94173694],
        [1.39063014, 1.48211152, 0.97430912]]])