<a href="https://colab.research.google.com/github/shernee/04_cmpe258/blob/main/Operations_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Scalar vector multiplication

a = torch.rand(1)
b = torch.rand(5, 3)
mult = torch.einsum('i, ij -> ij', [a, b])
print(a)
print(b)
print(mult)

tensor([0.2542])
tensor([[0.9818, 0.1692, 0.2384],
        [0.7258, 0.6678, 0.6200],
        [0.7074, 0.5768, 0.5534],
        [0.7542, 0.6208, 0.4449],
        [0.1048, 0.2223, 0.6567]])
tensor([[0.2496, 0.0430, 0.0606],
        [0.1845, 0.1697, 0.1576],
        [0.1798, 0.1466, 0.1406],
        [0.1917, 0.1578, 0.1131],
        [0.0266, 0.0565, 0.1669]])


In [ ]:
# Vector vector multiplication

a = torch.rand(2, 5)
b = torch.rand(5, 3)
mult = torch.einsum('ij, jk -> ik', [a, b])
print(a)
print(b)
print(mult)

tensor([[0.6429, 0.4204, 0.1272, 0.5873, 0.0031],
        [0.7863, 0.5485, 0.0711, 0.9759, 0.9929]])
tensor([[0.3160, 0.9855, 0.1188],
        [0.6517, 0.2639, 0.7850],
        [0.6204, 0.6317, 0.0065],
        [0.3744, 0.1599, 0.2280],
        [0.1682, 0.0522, 0.4415]])
tensor([[0.7764, 0.9188, 0.5424],
        [1.1824, 1.1724, 1.1853]])


In [ ]:
# Outer product

a = torch.arange(4)
b = torch.arange(3, 6)  
prod = torch.einsum('i,j -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([0, 1, 2, 3])
tensor([3, 4, 5])
tensor([[ 0,  0,  0],
        [ 3,  4,  5],
        [ 6,  8, 10],
        [ 9, 12, 15]])


In [ ]:
# Scalar dot product

a = torch.arange(9).reshape(3, 3)
b = torch.arange(6).reshape(3, 2)
prod = torch.einsum('ij, jk ->', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor(204)


In [ ]:
# Hadamard product

a = torch.arange(8).reshape(2, 4)
b = torch.arange(4, 12).reshape(2, 4)
prod = torch.einsum('ij, ij -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  5, 12, 21],
        [32, 45, 60, 77]])


In [ ]:
# Batch matrix multiplication

a = torch.randn(3, 3, 5)
b = torch.randn(3, 5, 2)
batch_mult = torch.einsum('bij, bjk -> bik', [a, b])
print(a)
print(b)
print(batch_mult)

tensor([[[-0.6773,  0.7815,  0.0976, -0.3376, -1.0016],
         [-0.2147,  0.5441, -0.1041, -1.5888, -0.1477],
         [ 0.4789,  0.1681,  0.2626,  0.1920,  1.5456]],

        [[ 0.4644,  0.4793, -0.8845,  0.4871,  0.0896],
         [ 0.1962, -1.5146, -0.0384, -1.5082,  2.0303],
         [-0.1432, -0.8256,  2.1222, -0.7460,  1.7938]],

        [[-2.4303, -0.3767, -1.2423,  1.7091, -0.2427],
         [ 1.1554,  0.7634, -1.5851, -0.2582, -0.1536],
         [ 0.2669, -0.1670, -1.0830,  0.7396,  1.6235]]])
tensor([[[ 0.0491, -0.9551],
         [ 1.1950, -1.3534],
         [-0.3555, -0.5985],
         [-0.4036,  0.3748],
         [-0.2693, -1.0826]],

        [[-0.4017, -0.1576],
         [-1.5601,  0.5673],
         [-1.0467,  1.2570],
         [ 0.7197,  0.4947],
         [-1.7960,  0.3878]],

        [[-1.0549,  0.3017],
         [ 0.3286,  1.7896],
         [-0.3106,  0.0359],
         [-0.3485, -0.6107],
         [ 1.1762, -1.3009]]])
tensor([[[ 1.2719,  0.4887],
         [ 1.3576, -

In [ ]:
# Tensor reduction

a = torch.randn(2, 3, 5, 7)
b = torch.randn(4, 1, 3, 11, 5)
reduction = torch.einsum('pqrs, tuqvr -> pstuv', [a, b])
print(a.shape, b.shape, reduction.shape)

torch.Size([2, 3, 5, 7]) torch.Size([4, 1, 3, 11, 5]) torch.Size([2, 7, 4, 1, 11])


In [ ]:
# Transpose

a = torch.arange(8).reshape(4, 2)
transpose = torch.einsum('ij -> ji', [a])
print(a)
print(transpose)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])


In [ ]:
# Bilinear transformation

a = torch.randn(2, 3)
b = torch.randn(3, 3, 4)
c = torch.randn(2, 4)
bilinear = torch.einsum('ik, jkl, il -> ij', [a, b, c])
print(a)
print(b)
print(c)
print(bilinear)

tensor([[ 1.0194, -1.0325,  1.1552],
        [ 1.7109,  0.6803, -0.2855]])
tensor([[[-6.1467e-01,  1.1213e+00, -8.7369e-01,  7.0915e-01],
         [-2.5071e+00,  6.4044e-01, -2.8877e-01, -6.7373e-01],
         [-2.8574e-01,  2.3551e+00,  6.9576e-01,  1.7975e-01]],

        [[ 7.8964e-01,  2.2677e-01,  8.7683e-03,  1.6208e-01],
         [-1.0357e+00,  9.0935e-01, -2.6189e-01,  1.0951e+00],
         [ 6.7263e-01, -3.5130e-01,  9.0431e-01, -7.5851e-01]],

        [[ 1.2006e+00, -8.0647e-01,  1.0881e+00,  1.8557e-03],
         [ 1.5820e+00, -6.4618e-01, -2.9748e-01,  8.3277e-01],
         [ 1.0650e+00,  3.0839e-01, -8.7738e-01,  1.1741e+00]]])
tensor([[ 0.8010, -1.1297,  0.8869, -0.6142],
        [ 1.2567, -1.2474, -0.3489,  1.5471]])
tensor([[-3.1221,  5.6872,  0.4812],
        [-3.7124,  1.2538,  5.6274]])


In [ ]:
# Attention

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

# Parameters
# [hidden_dimension]
bM, br, w = random_tensors([7], num=3, requires_grad=True)
# [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = torch.einsum('ik, kl -> il', [ht, Wh]) + torch.einsum('ik, kl -> il', [rt1, Wr])

  Mt = torch.tanh(torch.einsum('ijk, kl -> ijl', [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  
  # [batch_size x sequence_length]
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w])) 
  
  # [batch_size x hidden_dimension]
  rt = torch.einsum('ijk, ij -> ik', [Y, at]) + torch.tanh(torch.einsum('ij, jk -> ik', [rt1, Wt]) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = torch.randn(3,5,7)
# [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

rt, at = attention(Y, ht, rt1)

print(at)

tensor([[0.1494, 0.3332, 0.3192, 0.1044, 0.0939],
        [0.0530, 0.5588, 0.2151, 0.0731, 0.1000],
        [0.2654, 0.0522, 0.3481, 0.2986, 0.0356]], grad_fn=<SoftmaxBackward0>)


<ipython-input-54-0f495568e4dc>:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w]))


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + torch.tanh(torch.einsum('bk, aki -> bai', [zl, W]) + b)

# Inputs - [batch_size x hidden_dimension]
zl = torch.randn(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = torch.randn(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = torch.randn(5, 3, 3)

transition(zl)

tensor([[[ 0.7924, -0.5440,  1.1019],
         [-0.7051, -0.2637, -0.3537],
         [-0.8080,  1.0011,  1.4171],
         [-0.2296, -0.1790,  1.2798],
         [ 1.0797,  0.5839, -0.2840]],

        [[ 0.0376, -1.3244,  0.5081],
         [-0.2335, -1.2459,  0.0876],
         [-1.0806, -0.3098,  1.3159],
         [-0.1106, -0.8778, -0.0471],
         [ 0.5811,  0.4377, -0.5074]]])