<a href="https://colab.research.google.com/github/shernee/04_cmpe258/blob/main/Operations_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
#import torch.nn.functional as F

In [ ]:
# Scalar vector multiplication

a = tf.random.normal([1])
b = tf.random.normal([2, 3])
mult = tf.einsum('k, ij -> ij', a, b)
print(a)
print(b)
print(mult)

tf.Tensor([0.19171943], shape=(1,), dtype=float32)
tf.Tensor(
[[-0.6751951 -1.8173677 -0.5352537]
 [ 1.6614612  1.4489069  0.0434817]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.12944801 -0.3484247  -0.10261853]
 [ 0.3185344   0.2777836   0.00833629]], shape=(2, 3), dtype=float32)


In [ ]:
# Vector vector multiplication

a = tf.random.normal([3, 4])
b = tf.random.normal([4, 2])
mult = tf.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

tf.Tensor(
[[ 1.2622807  -0.63826555  2.2889252  -0.49091038]
 [-1.2988809   1.2458606  -1.324583   -0.05150975]
 [-0.8819322  -1.4783493  -1.7474608   0.8468661 ]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-0.22292201 -0.7709857 ]
 [ 0.33337048  0.35876635]
 [-0.15169476 -0.07374223]
 [-0.12199151  0.53240466]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[-0.7815001  -1.632342  ]
 [ 0.9120983   1.5186453 ]
 [-0.13446572  0.7293123 ]], shape=(3, 2), dtype=float32)


In [ ]:
# Outer product

a = tf.range(5)
b = tf.range(4, 7)  
prod = tf.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0  0  0]
 [ 4  5  6]
 [ 8 10 12]
 [12 15 18]
 [16 20 24]], shape=(5, 3), dtype=int32)


In [ ]:
# Scalar dot product

a = tf.range(12)
a = tf.reshape(a, [4, 3])

b = tf.range(6)
b = tf.reshape(b, [3, 2])

prod = tf.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(362, shape=(), dtype=int32)


In [ ]:
# Hadamard product

a = tf.range(8)
a = tf.reshape(a, [2, 4])

b = tf.range(4, 12)
b = tf.reshape(b, [2, 4])

prod = tf.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)

tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  5  6  7]
 [ 8  9 10 11]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 0  5 12 21]
 [32 45 60 77]], shape=(2, 4), dtype=int32)


In [ ]:
# Batch matrix multiplication

a = tf.random.normal([5, 3, 2])
b = tf.random.normal([5, 2, 4])
batch_mult = tf.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

tf.Tensor(
[[[-2.8027813   0.05627567]
  [-0.4969179  -0.35014513]
  [ 0.6666803   1.6293976 ]]

 [[-0.8813847  -0.15695372]
  [-0.3237835   0.5977659 ]
  [-1.7892      0.7839804 ]]

 [[ 0.7625496   0.926387  ]
  [-2.538035   -0.65173554]
  [ 0.7334915  -1.0678233 ]]

 [[ 0.18024161 -1.1939605 ]
  [-0.03087219 -0.96784246]
  [ 1.346309    0.9016271 ]]

 [[ 2.0276449  -1.3751156 ]
  [ 0.06358938 -0.6973285 ]
  [ 1.1284546  -2.048345  ]]], shape=(5, 3, 2), dtype=float32)
tf.Tensor(
[[[ 0.6934396   0.9255606   0.85550207 -0.65360856]
  [ 1.0813301   0.2515487   0.30121288  1.0044328 ]]

 [[-0.07993804 -0.24022879 -0.19062996  1.7045192 ]
  [-0.6170468  -0.616183    0.41338527 -0.5702826 ]]

 [[ 0.10178208  0.3510667  -1.4833367   0.03449396]
  [-0.36437795  1.2565476   0.30796584 -0.17922501]]

 [[ 1.2045647  -1.316001    0.839442   -0.63842297]
  [ 0.94192314 -1.3906146   0.52955145  0.9664694 ]]

 [[-0.5653841  -1.2534456  -0.28217784  0.7999384 ]
  [ 0.3267898  -0.9139939  -0.7527964  

In [ ]:
# Tensor reduction

a = tf.random.normal([3, 3, 5, 4])
b = tf.random.normal([5, 1, 3, 11, 5])
reduction = tf.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(3, 3, 5, 4) (5, 1, 3, 11, 5) (3, 4, 5, 1, 11)


In [ ]:
# Transpose

a = tf.range(10)
a = tf.reshape(a, [5, 2])
transpose = tf.einsum('ij -> ji', a)
print(a)
print(transpose)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]], shape=(5, 2), dtype=int32)
tf.Tensor(
[[0 2 4 6 8]
 [1 3 5 7 9]], shape=(2, 5), dtype=int32)


In [ ]:
# Bilinear transformation

a = tf.random.normal([2, 4])
b = tf.random.normal([3, 4, 4])
c = tf.random.normal([2, 4])
bilinear = tf.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

tf.Tensor(
[[-0.69732547 -0.77136916  0.83661866  1.1554966 ]
 [-0.22652628  0.93995774 -0.7725664   0.64542073]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[[ 2.2291393   1.1789131   0.12577243 -0.7663467 ]
  [ 2.6311333  -0.8665867   0.42036626 -0.50369185]
  [-0.3234374   1.0818207   0.70052564  1.003704  ]
  [ 0.8993542   0.3895857   1.7453076   2.0710406 ]]

 [[ 0.9305819  -0.34105617 -0.7941161  -0.722856  ]
  [-0.7132311   0.38948318 -0.6728501   1.6471618 ]
  [-1.955623    1.5580286   1.305597    0.26125208]
  [ 1.2755817   0.13867652  0.7299397   2.1309633 ]]

 [[-0.89681286 -0.42436007 -0.549283   -0.0741457 ]
  [ 0.3167305   1.9568026  -0.32572198 -0.2829573 ]
  [ 0.7185003   0.16662729 -1.7866851   2.0417924 ]
  [-0.76318866  0.48879415 -1.5704789   0.33848763]]], shape=(3, 4, 4), dtype=float32)
tf.Tensor(
[[ 2.2478132  -0.66521204  0.13567212  0.493652  ]
 [-0.613899    0.0791862  -0.32404265 -1.3378973 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-4.7791133  -0.16535544  

In [ ]:
# Attention

# Parameters
# [hidden_dimension]
bM = tf.random.normal([6])
br = tf.random.normal([6]) 
w = tf.random.normal([6])
# [hidden_dimension x hidden_dimension]
WY = tf.random.normal([6, 6])
Wh = tf.random.normal([6, 6])
Wr = tf.random.normal([6, 6])
Wt = tf.random.normal([6, 6])

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = tf.einsum('ik, kl -> il', ht, Wh) + tf.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = tf.expand_dims(tmp, 1)
  tmp_tiled = tf.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = tf.tanh(tf.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = tf.nn.softmax(tf.einsum('ijk, k -> ij', Mt, w)) 
  
  # [batch_size x hidden_dimension]
  rt = tf.einsum('ijk, ij -> ik', Y, at) + tf.tanh(tf.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = tf.random.normal([3,5,6])
# [batch_size x hidden_dimension]
ht = tf.random.normal([3, 6])
rt1 = tf.random.normal([3, 6])

rt, at = attention(Y, ht, rt1)

print(at)

tf.Tensor(
[[3.9871472e-01 5.0576282e-01 2.2192875e-02 5.5489678e-02 1.7839910e-02]
 [9.1844767e-01 6.6425115e-02 4.8836053e-04 3.1973205e-03 1.1441520e-02]
 [5.7841055e-02 2.4292566e-01 2.1445148e-01 2.4289948e-01 2.4188237e-01]], shape=(3, 5), dtype=float32)


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return tf.expand_dims(zl, 1) + tf.tanh(tf.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = tf.random.normal([2, 3])
# Parameters - [num_actions x hidden_dimension]
b = tf.random.normal([5, 3])
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = tf.random.normal([5, 3, 3])

transition(zl)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[ 3.3654652 , -2.9039857 , -1.318193  ],
        [ 1.386427  , -2.8705063 ,  0.17979407],
        [ 1.370734  , -0.9170044 ,  0.6753818 ],
        [ 3.0276241 , -1.1529515 , -1.3191075 ],
        [ 3.3630497 , -2.589436  ,  0.67522156]],

       [[ 0.6627935 ,  0.6072949 , -0.15422049],
        [-0.59032273,  0.63858974, -0.0712972 ],
        [ 0.8012289 , -0.03708696,  1.3189734 ],
        [ 0.90956736, -0.00667107, -0.44518325],
        [ 0.22970219, -1.039972  ,  1.2892215 ]]], dtype=float32)>