<a href="https://colab.research.google.com/github/shernee/04_cmpe258/blob/main/Operations_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Scalar vector multiplication

a = torch.rand(1)
b = torch.rand(5, 2)
mult = torch.einsum('i, ij -> ij', [a, b])
print(a)
print(b)
print(mult)

tensor([0.5007])
tensor([[0.5422, 0.1373],
        [0.6885, 0.4197],
        [0.7236, 0.2490],
        [0.6489, 0.1423],
        [0.9284, 0.9190]])
tensor([[0.2715, 0.0688],
        [0.3447, 0.2101],
        [0.3623, 0.1247],
        [0.3249, 0.0713],
        [0.4648, 0.4601]])


In [ ]:
# Vector vector multiplication

a = torch.rand(3, 4)
b = torch.rand(4, 2)
mult = torch.einsum('ij, jk -> ik', [a, b])
print(a)
print(b)
print(mult)

tensor([[0.9670, 0.5860, 0.4055, 0.1666],
        [0.2807, 0.7668, 0.8024, 0.5411],
        [0.7601, 0.4636, 0.4499, 0.8677]])
tensor([[0.8703, 0.8567],
        [0.0394, 0.2347],
        [0.8992, 0.9251],
        [0.8815, 0.0520]])
tensor([[1.3761, 1.3496],
        [1.4730, 1.1908],
        [1.8493, 1.2214]])


In [ ]:
# Outer product

a = torch.arange(4)
b = torch.arange(2, 7)  
prod = torch.einsum('i,j -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([0, 1, 2, 3])
tensor([2, 3, 4, 5, 6])
tensor([[ 0,  0,  0,  0,  0],
        [ 2,  3,  4,  5,  6],
        [ 4,  6,  8, 10, 12],
        [ 6,  9, 12, 15, 18]])


In [ ]:
# Scalar dot product

a = torch.arange(12).reshape(4, 3)
b = torch.arange(6).reshape(3, 2)
prod = torch.einsum('ij, jk ->', [a, b])
print(a)
print(b)
print(prod)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor(362)


In [ ]:
# Hadamard product

a = torch.arange(8).reshape(2, 4)
b = torch.arange(4, 12).reshape(2, 4)
prod = torch.einsum('ij, ij -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  5, 12, 21],
        [32, 45, 60, 77]])


In [ ]:
# Batch matrix multiplication

a = torch.randn(5, 3, 2)
b = torch.randn(5, 2, 4)
batch_mult = torch.einsum('bij, bjk -> bik', [a, b])
print(a)
print(b)
print(batch_mult)

tensor([[[-1.4553e+00, -1.7111e-01],
         [ 4.0565e-01, -8.3465e-01],
         [-4.7875e-01,  1.2393e+00]],

        [[-1.4233e-01, -5.5644e-02],
         [ 6.4517e-01, -2.4985e-01],
         [ 2.8128e+00,  4.4208e-01]],

        [[-5.9963e-01,  3.3907e-02],
         [ 9.6385e-02, -4.1245e-01],
         [-1.9093e-01, -2.0003e-01]],

        [[ 8.7891e-01, -8.6112e-01],
         [ 8.6214e-01,  1.0268e-03],
         [ 5.1808e-01,  1.8051e-01]],

        [[ 2.1406e-01, -1.5639e-01],
         [-5.1803e-01,  2.9477e-01],
         [-7.8507e-01, -8.9058e-01]]])
tensor([[[ 0.0746,  1.0408,  0.5979, -0.5060],
         [ 0.1247, -0.4264, -0.2611,  0.7767]],

        [[-0.3301, -0.5288,  0.0081,  1.6001],
         [ 0.1628,  0.3661,  0.4332, -1.1243]],

        [[-0.0876, -0.4243,  1.3762,  1.0380],
         [-0.1134,  0.1387,  0.2034,  0.7833]],

        [[ 0.6693, -0.0103,  1.8785,  0.9205],
         [ 0.0119, -1.5305, -0.1146,  1.4296]],

        [[-0.9847,  0.1808,  0.8950, -0.0280],
    

In [ ]:
# Tensor reduction

a = torch.randn(3, 3, 5, 4)
b = torch.randn(5, 1, 3, 11, 5)
reduction = torch.einsum('pqrs, tuqvr -> pstuv', [a, b])
print(a.shape, b.shape, reduction.shape)

torch.Size([3, 3, 5, 4]) torch.Size([5, 1, 3, 11, 5]) torch.Size([3, 4, 5, 1, 11])


In [ ]:
# Transpose

a = torch.arange(10).reshape(5, 2)
transpose = torch.einsum('ij -> ji', [a])
print(a)
print(transpose)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])


In [ ]:
# Bilinear transformation

a = torch.randn(2, 4)
b = torch.randn(3, 4, 4)
c = torch.randn(2, 4)
bilinear = torch.einsum('ik, jkl, il -> ij', [a, b, c])
print(a)
print(b)
print(c)
print(bilinear)

tensor([[ 1.0684, -1.5061, -0.9277, -2.0462],
        [ 1.0035,  0.9128, -0.3480, -0.0150]])
tensor([[[ 0.6079,  0.8268,  0.6350, -1.1869],
         [-0.1083,  0.9952, -0.6336, -0.6504],
         [-1.2705, -1.8204,  0.7749, -0.4700],
         [ 2.0109,  1.3872, -1.0316, -1.0610]],

        [[-0.9354,  1.1307, -0.5839,  2.0572],
         [ 0.3872, -0.0847,  1.9612,  0.4865],
         [ 0.1876,  0.3049,  0.0899, -1.5961],
         [-0.1527,  1.5999, -0.9913, -0.3779]],

        [[ 0.5941,  0.2433,  1.8852,  0.2115],
         [ 1.2232, -1.0056, -0.5936, -0.8168],
         [-0.9382, -0.3067, -0.0343, -0.4532],
         [ 0.1750, -0.5382,  0.4577,  0.5255]]])
tensor([[ 1.5155, -1.5626,  0.3557,  0.3391],
        [-0.2585, -1.2897, -1.3806, -1.0695]])
tensor([[ 1.4023,  1.9620, -5.0075],
        [-1.2839, -5.9513, -1.2662]])


In [ ]:
# Attention

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

# Parameters
# [hidden_dimension]
bM, br, w = random_tensors([6], num=3, requires_grad=True)
# [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([6, 6], num=4, requires_grad=True)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = torch.einsum('ik, kl -> il', [ht, Wh]) + torch.einsum('ik, kl -> il', [rt1, Wr])

  Mt = torch.tanh(torch.einsum('ijk, kl -> ijl', [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  
  # [batch_size x sequence_length]
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w])) 
  
  # [batch_size x hidden_dimension]
  rt = torch.einsum('ijk, ij -> ik', [Y, at]) + torch.tanh(torch.einsum('ij, jk -> ik', [rt1, Wt]) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = torch.randn(3,5,6)
# [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 6], num=2)

rt, at = attention(Y, ht, rt1)

print(at)

tensor([[0.3064, 0.1261, 0.1296, 0.3212, 0.1166],
        [0.1670, 0.1798, 0.1275, 0.2898, 0.2359],
        [0.1555, 0.1757, 0.0619, 0.3698, 0.2371]], grad_fn=<SoftmaxBackward0>)


<ipython-input-12-ab904282b68c>:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w]))


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + torch.tanh(torch.einsum('bk, aki -> bai', [zl, W]) + b)

# Inputs - [batch_size x hidden_dimension]
zl = torch.randn(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = torch.randn(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = torch.randn(5, 3, 3)

transition(zl)

tensor([[[-0.9229, -0.2503, -0.4214],
         [-0.7416, -0.7648, -0.6006],
         [-1.9246, -1.0549, -0.6626],
         [-0.1298, -1.0461, -0.2297],
         [-1.2603,  0.4822,  1.2827]],

        [[ 1.6660,  0.5844,  1.8875],
         [ 0.2896, -1.2155,  0.7097],
         [ 0.3233,  0.3691,  1.7026],
         [ 0.4486, -1.3444,  2.2562],
         [ 2.2118, -1.3579,  1.4453]]])